import React, { useState, useEffect } from 'react';
import { adminManagementApi, compoundersApi } from '../services/api';
import { Search, ShieldAlert, Loader2, Eye, Printer, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export const AdminBilling: React.FC = () => {
  const [bills, setBills] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');
  
  // View Bill Modal State
  const [isOpen, setIsOpen] = useState(false);
  const [selectedBill, setSelectedBill] = useState<any>(null);

  const fetchBills = async () => {
    try {
      setLoading(true);
      const res = await adminManagementApi.getBills({ search });
      if (res.success) {
        setBills(res.bills || []);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const delayDebounce = setTimeout(() => {
      fetchBills();
    }, 300);
    return () => clearTimeout(delayDebounce);
  }, [search]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      
      {/* Control Bar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ position: 'relative', width: '280px' }}>
          <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: '#94a3b8' }}>
            <Search size={16} />
          </span>
          <input
            type="text"
            placeholder="Search by Bill Number, patient name..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            style={{
              width: '100%',
              padding: '8px 10px 8px 32px',
              border: '1px solid #cbd5e1',
              borderRadius: '10px',
              fontSize: '0.85rem',
              outline: 'none',
              boxSizing: 'border-box'
            }}
          />
        </div>
      </div>

      {/* List Table */}
      <div style={{ background: 'white', borderRadius: '16px', border: '1px solid #e2e8f0', padding: '20px', boxShadow: '0 1px 3px rgba(0,0,0,0.05)' }}>
        {loading && bills.length === 0 ? (
          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '200px' }}>
            <Loader2 className="animate-spin text-sky-600" size={32} />
          </div>
        ) : bills.length === 0 ? (
          <div style={{ padding: '40px 0', textAlign: 'center', color: '#94a3b8' }}>
            <ShieldAlert size={36} style={{ marginBottom: '8px' }} />
            <p style={{ margin: 0, fontSize: '0.9rem', fontWeight: 600 }}>No bills generated yet.</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
              <thead>
                <tr style={{ borderBottom: '2px solid #e2e8f0', textAlign: 'left', color: '#64748b' }}>
                  <th style={{ padding: '12px 8px', fontWeight: 700 }}>Bill Number</th>
                  <th style={{ padding: '12px 8px', fontWeight: 700 }}>Patient Name</th>
                  <th style={{ padding: '12px 8px', fontWeight: 700 }}>Doctor (Dept)</th>
                  <th style={{ padding: '12px 8px', fontWeight: 700 }}>Total Amount</th>
                  <th style={{ padding: '12px 8px', fontWeight: 700 }}>Status</th>
                  <th style={{ padding: '12px 8px', fontWeight: 700 }}>Generated By</th>
                  <th style={{ padding: '12px 8px', fontWeight: 700 }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {bills.map(bill => (
                  <tr key={bill._id} style={{ borderBottom: '1px solid #f1f5f9', color: '#334155' }}>
                    <td style={{ padding: '12px 8px', fontWeight: 700, color: '#0284c7' }}>{bill.billNumber}</td>
                    <td style={{ padding: '12px 8px', fontWeight: 600 }}>{bill.patientName}</td>
                    <td style={{ padding: '12px 8px' }}>{bill.doctorName} <span style={{ color: '#64748b' }}>({bill.departmentName})</span></td>
                    <td style={{ padding: '12px 8px', fontWeight: 700 }}>₹ {bill.total.toFixed(2)}</td>
                    <td style={{ padding: '12px 8px' }}>
                      <span style={{
                        padding: '3px 8px',
                        borderRadius: '6px',
                        fontSize: '0.72rem',
                        fontWeight: 700,
                        background: bill.paymentStatus === 'Paid' ? '#d1fae5' : '#fee2e2',
                        color: bill.paymentStatus === 'Paid' ? '#065f46' : '#991b1b'
                      }}>
                        {bill.paymentStatus} ({bill.paymentMode})
                      </span>
                    </td>
                    <td style={{ padding: '12px 8px' }}>{bill.createdBy}</td>
                    <td style={{ padding: '12px 8px', display: 'flex', gap: '8px' }}>
                      <button
                        onClick={() => {
                          setSelectedBill(bill);
                          setIsOpen(true);
                        }}
                        style={{
                          background: '#f1f5f9',
                          border: '1px solid #cbd5e1',
                          borderRadius: '8px',
                          padding: '6px 10px',
                          cursor: 'pointer',
                          display: 'inline-flex',
                          alignItems: 'center',
                          gap: '4px',
                          fontSize: '0.75rem',
                          fontWeight: 600
                        }}
                      >
                        <Eye size={12} /> View
                      </button>
                      <button
                        onClick={() => compoundersApi.printBillPdf(bill._id)}
                        style={{
                          background: '#e0f2fe',
                          color: '#0369a1',
                          border: '1px solid #bae6fd',
                          borderRadius: '8px',
                          padding: '6px 10px',
                          cursor: 'pointer',
                          display: 'inline-flex',
                          alignItems: 'center',
                          gap: '4px',
                          fontSize: '0.75rem',
                          fontWeight: 600
                        }}
                      >
                        <Printer size={12} /> Print
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* VIEW DETAILS MODAL */}
      <AnimatePresence>
        {isOpen && selectedBill && (
          <div style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            background: 'rgba(15, 23, 42, 0.4)',
            backdropFilter: 'blur(8px)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 900
          }}>
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              style={{
                background: 'white',
                borderRadius: '20px',
                width: '100%',
                maxWidth: '520px',
                padding: '28px',
                boxShadow: '0 25px 50px -12px rgba(0,0,0,0.15)',
                boxSizing: 'border-box'
              }}
            >
              <h3 style={{ margin: '0 0 16px 0', fontSize: '1.2rem', fontWeight: 800, color: '#0284c7', display: 'flex', gap: '8px', alignItems: 'center' }}>
                <FileText size={20} /> Invoice details {selectedBill.billNumber}
              </h3>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', fontSize: '0.82rem', marginBottom: '20px' }}>
                <div style={{ borderBottom: '1px solid #f1f5f9', paddingBottom: '6px' }}>
                  <span style={{ color: '#64748b', fontWeight: 600 }}>Patient Name:</span>{' '}
                  <span style={{ color: '#1e293b', fontWeight: 700 }}>{selectedBill.patientName}</span>
                </div>
                <div style={{ borderBottom: '1px solid #f1f5f9', paddingBottom: '6px' }}>
                  <span style={{ color: '#64748b', fontWeight: 600 }}>Doctor Consulting:</span>{' '}
                  <span style={{ color: '#1e293b', fontWeight: 700 }}>{selectedBill.doctorName} ({selectedBill.departmentName})</span>
                </div>
                <div style={{ borderBottom: '1px solid #f1f5f9', paddingBottom: '6px' }}>
                  <span style={{ color: '#64748b', fontWeight: 600 }}>Payment Info:</span>{' '}
                  <span style={{ color: '#065f46', fontWeight: 700 }}>{selectedBill.paymentStatus} ({selectedBill.paymentMode})</span>
                </div>
                <div style={{ borderBottom: '1px solid #f1f5f9', paddingBottom: '6px' }}>
                  <span style={{ color: '#64748b', fontWeight: 600 }}>Invoice Date:</span>{' '}
                  <span style={{ color: '#1e293b', fontWeight: 700 }}>{new Date(selectedBill.createdAt).toLocaleString('en-IN')}</span>
                </div>
                <div style={{ borderBottom: '1px solid #f1f5f9', paddingBottom: '6px' }}>
                  <span style={{ color: '#64748b', fontWeight: 600 }}>Issued By:</span>{' '}
                  <span style={{ color: '#1e293b', fontWeight: 700 }}>{selectedBill.createdBy}</span>
                </div>
              </div>

              {/* Items List */}
              <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '12px', padding: '16px', marginBottom: '20px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 700, fontSize: '0.78rem', color: '#64748b', borderBottom: '1px solid #cbd5e1', paddingBottom: '6px', marginBottom: '8px' }}>
                  <span>Service Name</span>
                  <span>Price</span>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', fontSize: '0.8rem', color: '#334155' }}>
                  {selectedBill.services.map((item: any, idx: number) => (
                    <div key={idx} style={{ display: 'flex', justifyContent: 'space-between' }}>
                      <span>{item.name}</span>
                      <span style={{ fontWeight: 600 }}>₹ {item.price.toFixed(2)}</span>
                    </div>
                  ))}
                </div>
                <div style={{ borderTop: '1px solid #cbd5e1', marginTop: '12px', paddingTop: '8px', display: 'flex', justifyContent: 'space-between', fontWeight: 800, fontSize: '0.88rem', color: '#0284c7' }}>
                  <span>Total Paid:</span>
                  <span>₹ {selectedBill.total.toFixed(2)}</span>
                </div>
              </div>

              <div style={{ display: 'flex', gap: '14px', justifyContent: 'end' }}>
                <button
                  onClick={() => setIsOpen(false)}
                  style={{
                    background: '#f1f5f9',
                    border: 'none',
                    borderRadius: '8px',
                    padding: '8px 16px',
                    fontSize: '0.8rem',
                    fontWeight: 700,
                    cursor: 'pointer'
                  }}
                >
                  Close
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
};
